mkdir "WSDA" 
ln "name/winter wheat.CS_crop" "WSDA/WinWheat.CS_crop"
ln "name/alfalfa.CS_crop" "WSDA/Alfalfa.CS_crop"
ln "name/potato.CS_crop" "WSDA/Potatoes.CS_crop"
ln "name/grain corn.CS_crop" "WSDA/Corn.CS_crop"
ln "name/pasture.CS_crop" "WSDA/Pasture_Grass.CS_crop"
ln "name/apple.CS_crop" "WSDA/Apples.CS_crop"
ln "name/bean dry.CS_crop" "WSDA/DryBeans.CS_crop"
ln "name/sugarbeet.CS_crop" "WSDA/Sugarbeets.CS_crop"
ln "name/pea.CS_crop" "WSDA/Peas.CS_crop"
ln "name/pasture.CS_crop" "WSDA/GrassHay.CS_crop"
ln "name/lentil.CS_crop" "WSDA/Lentils.CS_crop"
ln "name/pasture.CS_crop" "WSDA/Timothy.CS_crop"
ln "name/sweet corn.CS_crop" "WSDA/SweetCorn.CS_crop"
ln "name/pasture.CS_crop" "WSDA/NLCDPasture_Hay.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/BluegrassSeed.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/BromegrassSeed.CS_crop"
ln "name/alfalfa.CS_crop" "WSDA/AlfalfaOrGrassHay.CS_crop"
ln "name/cherry.CS_crop" "WSDA/CherryOrchard.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Onions.CS_crop"
ln "name/pasture.CS_crop" "WSDA/OtherHays.CS_crop"
ln "name/spring wheat.CS_crop" "WSDA/SpgWheat.CS_crop"
ln "name/lentil.CS_crop" "WSDA/Chickpea.CS_crop"
ln "name/mint.CS_crop" "WSDA/Mint.CS_crop"
ln "name/wine grape.CS_crop" "WSDA/Grapes.CS_crop"
ln "name/oat.CS_crop" "WSDA/Oats.CS_crop"
ln "name/hops.CS_crop" "WSDA/Hops.CS_crop"
ln "name/pasture.CS_crop" "WSDA/Pasture.CS_crop"
ln "name/juice grape.CS_crop" "WSDA/GrapeJuice.CS_crop"
ln "name/pea.CS_crop" "WSDA/PeaGreen.CS_crop"
ln "name/canola.CS_crop" "WSDA/Canola.CS_crop"
ln "name/apple.CS_crop" "WSDA/Pear.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Seed_SodGrass.CS_crop"
ln "name/alfalfa seed.CS_crop" "WSDA/AlfalfaSeed.CS_crop"
ln "name/winter and spring wheat.CS_crop" "WSDA/Rye.CS_crop"
ln "name/generic berry.CS_crop" "WSDA/Caneberry.CS_crop"
ln "name/bean dry.CS_crop" "WSDA/BeanGreen.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Asparagus.CS_crop"
ln "name/winter and spring wheat.CS_crop" "WSDA/Triticale.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Carrots.CS_crop"
ln "name/generic berry.CS_crop" "WSDA/Blueberry.CS_crop"
ln "name/generic berry.CS_crop" "WSDA/Cranberry.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/RyegrassSeed.CS_crop"
ln "name/grain corn.CS_crop" "WSDA/CornSeed.CS_crop"
ln "name/pea.CS_crop" "WSDA/PeaSeed.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Squash.CS_crop"
ln "name/grain corn.CS_crop" "WSDA/Sorghum.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/Buckwheat.CS_crop"
ln "name/cherry.CS_crop" "WSDA/NectarineOrPeach.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/GrassSeed.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/FescueSeed.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/Sudangrass.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/SpinachSeed.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Garlic.CS_crop"
ln "name/pasture.CS_crop" "WSDA/CloverHay.CS_crop"
ln "name/potato.CS_crop" "WSDA/PotatoSeed.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/OtherCrops.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Watermelon.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Herbs.CS_crop"
ln "name/apple.CS_crop" "WSDA/OthTreeNuts.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Dill.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/CloverWildflowers.CS_crop"
ln "name/canola.CS_crop" "WSDA/MustardSeed.CS_crop"
ln "name/generic berry.CS_crop" "WSDA/Strawberries.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Cucumber.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Broccoli.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/BulbTulip.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/CarrotSeed.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Peppers.CS_crop"
ln "name/sugarbeet.CS_crop" "WSDA/SugarBeetSeed.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Cauliflower.CS_crop"
ln "name/grain corn.CS_crop" "WSDA/CornUnknown.CS_crop"
ln "name/sugarbeet.CS_crop" "WSDA/BeetSeed.CS_crop"
ln "name/apple.CS_crop" "WSDA/OrchardUnknown.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Cabbage.CS_crop"
ln "name/bean dry.CS_crop" "WSDA/BeanSeed.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/RadishSeed.CS_crop"
ln "name/apple.CS_crop" "WSDA/OthTreeFruits.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Rhubarb.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/OnionSeed.CS_crop"
ln "name/barley.CS_crop" "WSDA/OthSmallGrains.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/CilantroSeed.CS_crop"
ln "name/pasture seed.CS_crop" "WSDA/BromegrassSeed.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/BrusselsSproutsSeed.CS_crop"
ln "name/grain corn.CS_crop" "WSDA/SafflowerSeed.CS_crop"
ln "name/pasture.CS_crop" "WSDA/SwissChardSeed.CS_crop"
ln "name/walnut.CS_crop" "WSDA/Walnuts.CS_crop"
ln "name/spring wheat.CS_crop" "WSDA/CerealGrainUnknown.CS_crop"
ln "name/canola.CS_crop" "WSDA/Safflower.CS_crop"
ln "name/spring wheat.CS_crop" "WSDA/DurWheat.CS_crop"
ln "name/canola.CS_crop" "WSDA/Mustard.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/BulbDaffodil.CS_crop"
ln "name/grain corn.CS_crop" "WSDA/Sunflowers.CS_crop"
ln "name/generic vegetable.CS_crop" "WSDA/Radish.CS_crop"
ln "name/canola.CS_crop" "WSDA/Camelina.CS_crop"
ln "name/cherry.CS_crop" "WSDA/Peaches.CS_crop"
ln "name/canola.CS_crop" "WSDA/RapeSeed.CS_crop"
ln "name/barley.CS_crop" "WSDA/Barley.CS_crop"

#The currently are set as seed: MustardSeed PotatoSeed OnionSeed RadishSeed SpinachSeed SugarBeetSeed SwissChardSeed
#BromegrassSeed
#Seed:  BeetSeed
#Missing:Prunes Plums Greens NurseryOrchardOrVineyard
#NA: Soybeans Millet Flaxseed MisVegsFruits Woodland ChristmasTrees Wetlands Cantaloupe Vetch Pumpkin Turnip BulbDahlia ConiferSeed GreenManure
#DblCropBarley_Corn
#NA: NLCDPerennialIce_Snow	NLCDDeveloped_OpenSpace	NLCDDeveloped_LowIntensity	NLCDDeveloped_MediumIntensit	NLCDDeveloped_HighIntensity	NLCDBarren	NLCDDeciduousForest	NLCDEvergreenForest	NLCDMixedForest	NLCDShrubland	NLCDGrasslandHerbaceous	NLCDPasture_Hay	NLCDWoodyWetlands	NLCDHerbaceousWetlands	 NLCDOpenWater
