mkdir "code" 
ln "name/spring wheat.CS_crop" "code/210.CS_crop"
ln "name/alfalfa.CS_crop" "code/701.CS_crop"
ln "name/barley.CS_crop" "code/201.CS_crop"
ln "name/potato.CS_crop" "code/1827.CS_crop"
ln "name/grain corn.CS_crop" "code/204.CS_crop"
ln "name/pasture.CS_crop" "code/1208.CS_crop"
ln "name/apple.CS_crop" "code/1401.CS_crop"
ln "name/bean dry.CS_crop" "code/1803.CS_crop"
ln "name/sugarbeet.CS_crop" "code/1832.CS_crop"
ln "name/pea.CS_crop" "code/1824.CS_crop"
ln "name/pasture.CS_crop" "code/713.CS_crop"
ln "name/lentil.CS_crop" "code/1819.CS_crop"
ln "name/pasture.CS_crop" "code/722.CS_crop"
ln "name/sweet corn.CS_crop" "code/1814.CS_crop"
ln "name/pasture.CS_crop" "code/1206.CS_crop"
ln "name/pasture seed.CS_crop" "code/1503.CS_crop"
ln "name/alfalfa.CS_crop" "code/703.CS_crop"
ln "name/cherry.CS_crop" "code/1403.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1822.CS_crop"
ln "name/pasture.CS_crop" "code/1207.CS_crop"
ln "name/winter wheat.CS_crop" "code/218.CS_crop"
ln "name/lentil.CS_crop" "code/1813.CS_crop"
ln "name/mint.CS_crop" "code/1101.CS_crop"
ln "name/wine grape.CS_crop" "code/2002.CS_crop"
ln "name/oat.CS_crop" "code/206.CS_crop"
ln "name/hops.CS_crop" "code/901.CS_crop"
ln "name/pasture.CS_crop" "code/1205.CS_crop"
ln "name/juice grape.CS_crop" "code/2001.CS_crop"
ln "name/pea.CS_crop" "code/1825.CS_crop"
ln "name/canola.CS_crop" "code/1902.CS_crop"
ln "name/apple.CS_crop" "code/1409.CS_crop"
ln "name/generic vegetable.CS_crop" "code/509.CS_crop"
ln "name/alfalfa seed.CS_crop" "code/1501.CS_crop"
ln "name/winter and spring wheat.CS_crop" "code/207.CS_crop"
ln "name/generic berry.CS_crop" "code/107.CS_crop"
ln "name/lentil.CS_crop" "code/1804.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1802.CS_crop"
ln "name/winter and spring wheat.CS_crop" "code/209.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1810.CS_crop"
ln "name/generic berry.CS_crop" "code/102.CS_crop"
ln "name/generic berry.CS_crop" "code/103.CS_crop"
ln "name/pasture.CS_crop" "code/1517.CS_crop"
ln "name/grain corn.CS_crop" "code/1509.CS_crop"
ln "name/pea.CS_crop" "code/1513.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1831.CS_crop"
ln "name/grain corn.CS_crop" "code/720.CS_crop"
ln "name/pasture seed.CS_crop" "code/202.CS_crop"
ln "name/cherry.CS_crop" "code/1407.CS_crop"
ln "name/pasture seed.CS_crop" "code/1527.CS_crop"
ln "name/pasture seed.CS_crop" "code/1526.CS_crop"
ln "name/pasture seed.CS_crop" "code/721.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1519.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1817.CS_crop"
ln "name/pasture.CS_crop" "code/708.CS_crop"
ln "name/potato.CS_crop" "code/1515.CS_crop"
ln "name/generic vegetable.CS_crop" "code/724.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1001.CS_crop"
ln "name/generic vegetable.CS_crop" "code/723.CS_crop"
ln "name/apple.CS_crop" "code/1413.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1901.CS_crop"
ln "name/generic vegetable.CS_crop" "code/508.CS_crop"
ln "name/canola.CS_crop" "code/1523.CS_crop"
ln "name/generic berry.CS_crop" "code/106.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1815.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1807.CS_crop"
ln "name/generic vegetable.CS_crop" "code/505.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1507.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1826.CS_crop"
ln "name/sugarbeet.CS_crop" "code/1520.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1811.CS_crop"
ln "name/grain corn.CS_crop" "code/205.CS_crop"
ln "name/sugarbeet.CS_crop" "code/1502.CS_crop"
ln "name/apple.CS_crop" "code/1498.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1809.CS_crop"
ln "name/bean dry.CS_crop" "code/1522.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1516.CS_crop"
ln "name/apple.CS_crop" "code/1412.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1829.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1512.CS_crop"
ln "name/barley.CS_crop" "code/221.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1525.CS_crop"
ln "name/pasture.CS_crop" "code/1504.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1505.CS_crop"
ln "name/grain corn.CS_crop" "code/1518.CS_crop"
ln "name/pasture.CS_crop" "code/1521.CS_crop"
ln "name/walnut.CS_crop" "code/1411.CS_crop"
ln "name/spring wheat.CS_crop" "code/298.CS_crop"
ln "name/canola.CS_crop" "code/1907.CS_crop"
ln "name/spring wheat.CS_crop" "code/220.CS_crop"
ln "name/canola.CS_crop" "code/1904.CS_crop"
ln "name/generic vegetable.CS_crop" "code/506.CS_crop"
ln "name/grain corn.CS_crop" "code/222.CS_crop"
ln "name/generic vegetable.CS_crop" "code/1839.CS_crop"
ln "name/canola.CS_crop" "code/1905.CS_crop"
ln "name/cherry.CS_crop" "code/1408.CS_crop"
ln "name/canola.CS_crop" "code/1906.CS_crop"
